default:
  tags:
    - dace-runner-dev

stages:
  - test
  - preview
  - deploy

Test:
  stage: test
  image: python:3.9
  before_script:
    - pip install --upgrade pip
    - pip install .
    - pip install pytest
  script:
    # Build the .dacerc file
    - printf '[user]\nkey = apiKey:%s\n' "${TEST_API_KEY}" > tests/dev.dacerc
    # Build the config.ini file
    - printf "${TESTING_CONFIG_INI}" > tests/config.ini
    # Run the tests
    - pytest
  allow_failure: false

Preview:    
  stage: preview
  when: manual
  image: python:3.9
  needs: [Test]
  before_script:
    - pip install --upgrade pip
    - pip install .
    - pip install twine
    - pip install build
  script:
    # Build the package and push to test.pypi.org
    # Delete any existing builds
    - rm -rf dist/*

    # Build the package
    # This will create a tar.gz and .whl package under /dist
    # Change the version to include timestamp in PEP 440-compliant format
    - |
      BASE_VERSION=$(grep version pyproject.toml | cut -d'"' -f2)
      BASE_VERSION=${BASE_VERSION%.*}
      sed -i "s/version = .*/version = \"${BASE_VERSION}.dev$(date +%Y%m%d%H%M%S)\"/" pyproject.toml
    - python -m build
    - python -m twine check dist/*

    # Publish the package on https://test.pypi.org
    # TEST_PYPI_TOKEN is the token generated by https://test.pypi.org
    - python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p ${TEST_PYPI_TOKEN} --verbose

Deploy:
  stage: deploy
  image: python:3.9
  needs: 
    - Preview
  before_script:
    - pip install --upgrade pip
    - pip install .
    - pip install twine
    - pip install build
  script:
    # Push package to PyPI
    # Delete any existing builds
    - rm -rf dist/*

    # Build the package for release
    # This will create a tar.gz and .whl package under /dist
    - python -m build
    - python -m twine check dist/*


    # Publish the release package on https://test.pypi.org
    # TEST_PYPI_TOKEN is the token generated by https://test.pypi.org
    - python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p ${TEST_PYPI_TOKEN} --verbose

    # .. Publish the package on https://pypi.org
    # PYPI_TOKEN is the token generated by https://pypi.org
    - python -m twine upload dist/* -u __token__ -p ${PYPI_TOKEN} --verbose

  rules: # Only run on master or main branch
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"'
      when: manual
    - when: never