# https://stackoverflow.com/questions/65487163/python-sphinx-autodoc-not-rendering-on-readthedocs
# https://docs.readthedocs.io/en/stable/guides/poetry.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true


python:
  install:
    - method: pip
      path: .