import pytest

from dace_query import DaceClass
from dace_query.exoplanet import ExoplanetClass


@pytest.mark.parametrize("instance", [pytest.param("anon_dace_instance")])
def test_exoplanets_query_database_keys(instance, request):
    dace_instance: DaceClass = request.getfixturevalue(instance)
    instance = ExoplanetClass(dace_instance=dace_instance)

    results = instance.query_database(limit=10, output_format="dict")

    expected_keys = [
        'planet_name',
        'reference',
        'period',
        'planet_mass',
        'planet_radius',
        'planet_mass_rel_err',
        'planet_radius_rel_err',
        'host_name',
        'planet_letter',
        'tic_id',
        'gaia_dr3_id',
        'discovery_year',
        'discovery_method',
        'discovery_facility',
        'discovery_locale',
        'number_planets',
        'ads_link',
        'last_updated',
        'planet_mass_upper',
        'planet_mass_lower',
        'planet_msini',
        'planet_msini_upper',
        'planet_msini_lower',
        'planet_radius_upper',
        'planet_radius_lower',
        'period_upper',
        'period_lower',
        'semi_major_axis',
        'semi_major_axis_upper',
        'semi_major_axis_lower',
        'semi_major_axis_source',
        'ecc',
        'ecc_upper',
        'ecc_lower',
        'ecc_upper_flag',
        'insolation_flux',
        'insolation_flux_upper',
        'insolation_flux_lower',
        'equilibrium_temp',
        'equilibrium_temp_upper',
        'equilibrium_temp_lower',
        'inclination',
        'inclination_upper',
        'inclination_lower',
        'projected_obliquity',
        'projected_obliquity_upper',
        'projected_obliquity_lower',
        'projected_obliquity_ref',
        'epoch_periastron',
        'epoch_periastron_upper',
        'epoch_periastron_lower',
        'argument_periastron',
        'argument_periastron_upper',
        'argument_periastron_lower',
        'impact_parameter',
        'impact_parameter_upper',
        'impact_parameter_lower',
        'impact_parameter_source',
        'transit_depth',
        'transit_depth_upper',
        'transit_depth_lower',
        'transit_depth_source',
        'transit_duration',
        'transit_duration_upper',
        'transit_duration_lower',
        'transit_midpoint',
        'transit_midpoint_upper',
        'transit_midpoint_lower',
        'measured_rv_semi_amplitude',
        'measured_rv_semi_amplitude_upper',
        'measured_rv_semi_amplitude_lower',
        'spectral_type',
        'stellar_eff_temp',
        'stellar_eff_temp_upper',
        'stellar_eff_temp_lower',
        'stellar_radius',
        'stellar_radius_upper',
        'stellar_radius_lower',
        'stellar_mass',
        'stellar_mass_upper',
        'stellar_mass_lower',
        'stellar_metallicity',
        'stellar_metallicity_upper',
        'stellar_metallicity_lower',
        'stellar_metallicity_ratio',
        'stellar_luminosity',
        'stellar_luminosity_upper',
        'stellar_luminosity_lower',
        'stellar_surface_gravity',
        'stellar_surface_gravity_upper',
        'stellar_surface_gravity_lower',
        'stellar_age',
        'stellar_age_upper',
        'stellar_age_lower',
        'stellar_rotational_velocity',
        'stellar_rotational_velocity_upper',
        'stellar_rotational_velocity_lower',
        'stellar_rotational_period',
        'stellar_rotational_period_upper',
        'stellar_rotational_period_lower',
        'v_mag',
        'v_mag_upper',
        'v_mag_lower',
        'j_mag',
        'j_mag_upper',
        'j_mag_lower',
        'k_mag',
        'k_mag_upper',
        'k_mag_lower',
        'distance',
        'distance_upper',
        'distance_lower',
        'right_ascension',
        'right_ascension_err',
        'declination',
        'declination_err',
        'parallax',
        'parallax_err',
        'radial_velocity',
        'radial_velocity_err',
        'teff_gaia_dr3',
        'teff_gaia_dr3_upper',
        'teff_gaia_dr3_lower',
        'feh_gaia_dr3',
        'feh_gaia_dr3_upper',
        'feh_gaia_dr3_lower',
        'stellar_luminosity_gaia_dr3',
        'stellar_luminosity_gaia_dr3_upper',
        'stellar_luminosity_gaia_dr3_lower',
        'logg_gaia_dr3',
        'logg_gaia_dr3_upper',
        'logg_gaia_dr3_lower',
        'stellar_age_gaia_dr3',
        'stellar_age_gaia_dr3_upper',
        'stellar_age_gaia_dr3_lower',
        'expected_rv_semi_amplitude',
        'planet_density',
        'planet_density_upper',
        'planet_density_lower',
        'insolation_flux_computed',
        'insolation_flux_computed_upper',
        'insolation_flux_computed_lower',
        'equilibrium_temp_computed',
        'equilibrium_temp_computed_upper',
        'equilibrium_temp_computed_lower',
        'transmission_spectroscopy_metric',
        'emission_spectroscopy_metric',
        'binary_projected_separation',
        'binary_angular_seperation_computed',
        'companion_gaia_dr3_id',
        'companion_g_mag',
        'companion_gmag_host',
        'companion_gbp_grp',
        'companion_teff_gaia_dr3',
        'companion_teff_gaia_dr3_upper',
        'companion_teff_gaia_dr3_lower',
        'companion_feh_gaia_dr3',
        'companion_feh_gaia_dr3_upper',
        'companion_feh_gaia_dr3_lower',
        'companion_stellar_luminosity_gaia_dr3',
        'companion_stellar_luminosity_gaia_dr3_upper',
        'companion_stellar_luminosity_gaia_dr3_lower',
        'companion_logg_gaia_dr3',
        'companion_logg_gaia_dr3_upper',
        'companion_logg_gaia_dr3_lower',
        'number_stellar_companion',
    ]

    assert all(key in results.keys() for key in expected_keys)


@pytest.mark.parametrize(
    "instance, target",
    [
        pytest.param("anon_dace_instance", "L 98-59 c"),
        pytest.param("anon_dace_instance", "TOI-905 b"),
        pytest.param("anon_dace_instance", "unknown_target", marks=pytest.mark.xfail),
    ],
)
def test_exoplanet_query_database_specific_targets(
    instance, target, request: pytest.FixtureRequest
):
    dace_instance: DaceClass = request.getfixturevalue(instance)
    instance = ExoplanetClass(dace_instance=dace_instance)

    filters: dict = {"planet_name": {"equal": [target]}}
    results = instance.query_database(filters=filters, limit=10, output_format="dict")
    assert results
    assert all((target == obj) for obj in results["planet_name"])
